### ISSUE TITLE
`has-bigints` is not included as a dependency

### ISSUE THREAD

**Issue by mhassan1** [inspect-js/is-bigint#10]
`has-bigints` was added as a dependency in https://github.com/inspect-js/is-bigint/commit/7bb9d7ab42214c12ce25e9f0cfe2af769388c3bb; however, the dependency was not added to `package.json`.

In a script like this:
```js
require('is-bigint')
```

I get the following error:
```
node index.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'has-bigints'
Require stack:
- /Users/marc/projects/zzz/is-bigint/node_modules/is-bigint/index.js
```

**Comment by ljharb** [comment]
Whoops, thanks!
